version: '3.2'
services:
  web:
    # build: .
    image: test-aa
    ports:
      - "8181:80"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/monitoring
    restart: always
  db:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    restart: always
